// phrase-player.js — Pre-recorded Azure TTS audio file player
// Plays MP3 files generated by scripts/generate-azure-audio.py
// Falls back silently if a file fails to load (Web Speech API still works as backup)

let _muted = false;

export function setPhrasesMuted(muted) {
  _muted = muted;
}

/**
 * Play a single pre-recorded audio file.
 * Returns a Promise that resolves when playback ends (or on any error).
 */
export function playFile(path) {
  return new Promise(resolve => {
    if (_muted) { resolve(); return; }

    const audio = new Audio(path);
    audio.volume = 1.0;

    const safety = setTimeout(() => resolve(), 10000);
    const done = () => { clearTimeout(safety); resolve(); };

    audio.addEventListener('ended', done, { once: true });
    audio.addEventListener('error', done, { once: true });

    audio.play().catch(() => done());
  });
}

/**
 * Play an array of segments in order.
 * Each segment: { type: 'file', path } | { type: 'gap', ms }
 */
export async function playSequence(segments) {
  for (const seg of segments) {
    if (_muted) return;
    if (seg.type === 'file') {
      await playFile(seg.path);
    } else if (seg.type === 'gap') {
      await new Promise(r => setTimeout(r, seg.ms));
    }
  }
}
