// tts-hybrid.js — High-level speech functions using Azure pre-recorded audio
//
// Audio files live in audio/ (generated by scripts/generate-azure-audio.py).
// Dynamic content (player name) is spoken live via Web Speech API.
// All functions fall back silently if a file is missing.

import { speak } from './speech.js';
import { playFile, playSequence } from './phrase-player.js';

const A = 'audio/';

// ── Path helpers ───────────────────────────────────────────────────────────
const NUM = (n) => `${A}num/num_${n}.mp3`;
const OP  = (op) => ({
  '+': `${A}op/op_plus.mp3`,
  '-': `${A}op/op_minus.mp3`,
  '×': `${A}op/op_times.mp3`,
  '÷': `${A}op/op_divided_by.mp3`,
}[op] ?? `${A}op/op_plus.mp3`);

const CORRECT_COUNT = 6;
let _lastCorrect = -1;

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * "How much is {a} {op} {b}?"
 * Composed from three pre-recorded files.
 */
export async function speakMath(a, op, b) {
  await playSequence([
    { type: 'file', path: `${A}q/how_much_is.mp3` },
    { type: 'gap',  ms: 60 },
    { type: 'file', path: NUM(a) },
    { type: 'gap',  ms: 60 },
    { type: 'file', path: OP(op) },
    { type: 'gap',  ms: 60 },
    { type: 'file', path: NUM(b) },
  ]);
}

/**
 * Random correct-feedback phrase ("Correct!", "Amazing!", etc.)
 * Avoids repeating the same variant twice in a row.
 */
export async function speakCorrect() {
  let idx;
  do { idx = Math.floor(Math.random() * CORRECT_COUNT); } while (idx === _lastCorrect && CORRECT_COUNT > 1);
  _lastCorrect = idx;
  await playFile(`${A}fb/fb_correct_${idx}.mp3`);
}

/**
 * Simple wrong feedback: "Almost! Try again."
 */
export async function speakWrong() {
  await playFile(`${A}fb/fb_wrong.mp3`);
}

/**
 * Wrong explanation with equation: "Almost! The answer is {n}, because {a} {op} {b} equals {n}."
 * All composed from pre-recorded fragments.
 */
export async function speakExplanation(a, op, b, answer) {
  await playSequence([
    { type: 'file', path: `${A}fb/fb_almost.mp3` },     // "Almost! The answer is"
    { type: 'gap',  ms: 80 },
    { type: 'file', path: NUM(answer) },
    { type: 'gap',  ms: 100 },
    { type: 'file', path: `${A}fb/fb_because.mp3` },    // "because"
    { type: 'gap',  ms: 80 },
    { type: 'file', path: NUM(a) },
    { type: 'gap',  ms: 60 },
    { type: 'file', path: OP(op) },
    { type: 'gap',  ms: 60 },
    { type: 'file', path: NUM(b) },
    { type: 'gap',  ms: 60 },
    { type: 'file', path: `${A}op/op_equals.mp3` },
    { type: 'gap',  ms: 60 },
    { type: 'file', path: NUM(answer) },
  ]);
}

/**
 * Wrong feedback without equation: "Almost! The answer is {n}."
 * Used for level types that don't expose a/b/op (e.g. BridgeBuilder fill-in).
 */
export async function speakWrongAnswer(answer) {
  await playSequence([
    { type: 'file', path: `${A}fb/fb_almost.mp3` },
    { type: 'gap',  ms: 80 },
    { type: 'file', path: NUM(answer) },
  ]);
}

/**
 * Mission intro: speak player name live via TTS, then play pre-recorded mission phrase.
 * Example: "Neil!" (live) + "Time to run!" (pre-recorded)
 */
export async function speakMissionIntro(missionKey, playerName) {
  if (playerName) await speak(`${playerName}!`, 1.1);
  const fileKey = missionKey.replace('-', '_');
  await playFile(`${A}mission/mission_${fileKey}.mp3`);
}

/**
 * Streak announcement ("Two in a row!", "Five in a row! You are a superhero!", etc.)
 */
export async function speakStreak(n) {
  const valid = [2, 3, 5, 10];
  if (valid.includes(n)) await playFile(`${A}streak/streak_${n}.mp3`);
}

/**
 * "You found them all!" — StarCollector completion.
 */
export async function speakFoundAll() {
  await playFile(`${A}misc/found_all.mp3`);
}
